apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: kube-system
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    targetRevision: v1.18.0
    chart: cilium
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true