apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test-pod
spec:
  containers:
    - name: longhorn-test
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Hello from Longhorn!" >> /data/hello.txt;
          sleep 3600;
      volumeMounts:
        - name: longhorn-volume
          mountPath: /data
  volumes:
    - name: longhorn-volume
      persistentVolumeClaim:
        claimName: longhorn-test-pvc
