apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.10.0
    chart: longhorn
  destination:
    name: in-cluster
    namespace: longhorn-system
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true