apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: default
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.2.0
    chart: traefik
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true