apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/s1monb/yggdrasil
        revision: HEAD
        directories:
          - path: apps/infra/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/s1monb/yggdrasil
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true