apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: lgtm-distributed
    repo: https://grafana.github.io/helm-charts/grafana
    version: 3.0.1
    namespace: lgmt
    releaseName: "lgtm-distributed"
    valuesFile: values.yaml
