apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.10.0
    releaseName: cilium
    namespace: longhorn-system