apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo
  template:
    metadata:
      labels:
        app: hugo
    spec:
      containers:
      - name: hugo
        image: ghcr.io/s1monb/mimir:latest
        ports:
        - containerPort: 1313

