apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 9.0.5
      chart: argo-cd
      helm:
        valueFiles:
          - $values/apps/argocd/values.yaml
    - repoURL: 'https://github.com/s1monb/yggdrasil'
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true